# NUMPY BASICS

In [1]:
import numpy as np

###  Numpy Arrays

In [5]:
# Transformando una python list en numpy array

mi_lista = [1, 2, 3, 7]

np.array(mi_lista)

array([1, 2, 3, 7])

In [7]:
# Transformando una matriz definida como lista de listas en el formato np.array

# PYTHON [LISTA[LISTA]]

A = [[1,2,3], [4,5,6], [7,8,9]]
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
# NUMPY ARRAY([LISTA[LISTA]])

np.array(A)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Es conveniente usar un np.array en lugar de una lista por la eficiencia que estas tienen en uso de memoria y tiempos de ejecución. 

### Numpy Built-in Methods 

In [29]:
""" 
    Arange:
        np.arange(inicial, final, paso(default=1)) 
        
        retornará un array de tamaño(final)     
        de la forma: 
            array([inicial, inicial+paso, ..., final-1])
"""
# Forma básica

print(np.arange(0,5))

print("\n--------------\n")

# desde 0 a 10 con paso 2

print(np.arange(0, 12, 2))

[0 1 2 3 4]

--------------

[ 0  2  4  6  8 10]


In [37]:
"""
    zeros, ones:
        np.zeros(n)
        
        retornará un array de dimension(n), tamaño(ñ) con ceros
        np.ones(n) cumple la misma funcion pero en lugar de ceros contrendrá unos.
"""

# Algunos ejemplos:

# Array con ceros de tamaño 3

print(np.zeros(3))

print("\n--------------\n")

# Array con ceros de tamaño 3x3

print(np.zeros((3,3)))

print("\n--------------\n")

# Array con unos de tamaño 3

print(np.ones(3))

print("\n--------------\n")

# Array con unos de tamaño 3x3

print(np.ones((3,3)))

print("\n--------------\n")

# Array con nueves de tamaño 4x4

print(np.ones((4,4))*9)

[0. 0. 0.]

--------------

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

--------------

[1. 1. 1.]

--------------

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

--------------

[[9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]
 [9. 9. 9. 9.]]


In [50]:
"""
    Linspace:
        np.linspace(inicial, final, n)
        
        retorna n números espaciados uniformemente dentro del intervalo [inicio, final]
"""

# Algunos ejemplos:

# 3 numeros uniformemente separados entre 0 y 10

print(np.linspace(0, 10, 3))

print("\n--------------\n")

# 60 numeros uniformemente separados entre 0 y 100

print(np.linspace(0, 100, 60))

[ 0.  5. 10.]

--------------

[  0.           1.69491525   3.38983051   5.08474576   6.77966102
   8.47457627  10.16949153  11.86440678  13.55932203  15.25423729
  16.94915254  18.6440678   20.33898305  22.03389831  23.72881356
  25.42372881  27.11864407  28.81355932  30.50847458  32.20338983
  33.89830508  35.59322034  37.28813559  38.98305085  40.6779661
  42.37288136  44.06779661  45.76271186  47.45762712  49.15254237
  50.84745763  52.54237288  54.23728814  55.93220339  57.62711864
  59.3220339   61.01694915  62.71186441  64.40677966  66.10169492
  67.79661017  69.49152542  71.18644068  72.88135593  74.57627119
  76.27118644  77.96610169  79.66101695  81.3559322   83.05084746
  84.74576271  86.44067797  88.13559322  89.83050847  91.52542373
  93.22033898  94.91525424  96.61016949  98.30508475 100.        ]


In [54]:
"""
    Eye:
        np.eye(n)
        
        crea una matriz identidad (con unos en la diagonal y ceros en las demas posiciones) de la forma NxN 
"""

np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [56]:
"""
    Rand:
        np.random.rand(n)
        
        Crea un array de tamaño n con numeros al azar dentro de una distribución uniforme entre 0 y 1.
"""

# Algunos ejemplos:

# un array con 20 numeros al azar dentro de la distribución uniforme entre 0 y 1.

print(np.random.rand(20))

print("\n--------------\n")

# una matriz de 4x4 con 16 numeros al azar dentro de la distribución uniforme entre 0 y 1.

print(np.random.rand(4,4))

[0.76965325 0.55191821 0.06950291 0.76199984 0.7324529  0.70684412
 0.98225314 0.904108   0.11617993 0.34265343 0.56980274 0.8338544
 0.134091   0.07058832 0.95412654 0.26518807 0.52188929 0.78596959
 0.3093543  0.40083342]

--------------

[[0.12973736 0.92913472 0.50166797 0.77010166]
 [0.40822338 0.24785845 0.01729589 0.18654008]
 [0.41070752 0.4312074  0.59165821 0.32542783]
 [0.5025657  0.58209271 0.61406556 0.03043362]]


### Distribución normal estandar
***
## $\varphi (x) = \frac{e^-{\frac{x^{2}}{2}}}{\sqrt{2\Pi}}$

In [62]:
"""
    Randn:
        np.random.randn(n)
        
        crea un array de tamaño n con muestras de la distribución normal estandar
"""

# Algunos ejemplos:

# 4 muestras de la distribución normal estandar

print(np.random.randn(4))

print("\n--------------\n")

# una matriz de la forma 2x2 con 4 muestras de la distribución normal estandar

print(np.random.randn(2,2))



[ 0.55715251  0.19854521 -1.05758291  1.47794725]

--------------

[[-0.17727521  0.85888876]
 [ 1.01862104  0.49923527]]


In [64]:
"""
    Randint:
        np.random.randint(I, F, N)
        
        retorna N(por defecto 1) valores aleatorios enteros entre I y F
"""

# Algunos ejemplos:

# Un número entero entre 2 y 9

print(np.random.randint(2,9))

print("\n--------------\n")

# 20 números enteros entre 35 y 80

print(np.random.randint(35,80,20))


3

--------------

[57 72 73 38 73 65 46 79 40 50 70 77 56 79 51 61 78 46 39 37]


## Algunas operaciones matemáticas:
***

In [72]:
x = 24

# Raiz cuadrada de x
print(np.sqrt(x))

print("\n--------------\n")

# Valor absoluto de x
print(np.absolute(x))

print("\n--------------\n")

# Seno de x
print(np.sin(x))

print("\n--------------\n")

# Coseno de x
print(np.cos(x))

print("\n--------------\n")
# sen(x)^2 + cos(x)^2 = 1 por regla trigonometrica
print((np.sin(x)**2) + (np.cos(x)**2))

print("\n--------------\n")
# Tangente de x
print(np.tan(x))

print("\n--------------\n")

# Logaritmo en base 2 de x
print(np.log2(x))

print("\n--------------\n")

# e^x
print(np.exp(x))


4.898979485566356

--------------

24

--------------

-0.9055783620066238

--------------

0.424179007336997

--------------

0.9999999999999999

--------------

-2.1348966977217008

--------------

4.584962500721156

--------------

26489122129.84347


## Arrays: operaciones, indexing y funciones.
***

In [100]:
# Definiendo un array para testear
arr = np.random.randint(1, 20, 25)
arr

array([13,  5,  9,  8, 14,  7,  8, 16,  8,  4,  6, 16, 14, 10, 14,  6, 13,
       16,  8, 13,  4,  6, 15, 14, 10])

In [101]:
# Shape: sirve para obtener la forma del array
arr.shape

(25,)

In [102]:
# Reshape: sirve para cambiar la forma del array, en este caso se transforma en una matriz 5x5
arr.reshape(5,5)

array([[13,  5,  9,  8, 14],
       [ 7,  8, 16,  8,  4],
       [ 6, 16, 14, 10, 14],
       [ 6, 13, 16,  8, 13],
       [ 4,  6, 15, 14, 10]])

In [103]:
# Dtype: sirve para obtener el tipo de variables que contiene el array
arr.dtype

dtype('int32')

In [104]:
# Obteniendo el valor de una posicion especifica del array
arr[6]

8

In [105]:
# Obteniendo valores dentro de un rango
arr[4:9]

array([14,  7,  8, 16,  8])

In [106]:
# Cambiando valores en un rango por un numero determinado
arr[0:3]=3
arr

array([ 3,  3,  3,  8, 14,  7,  8, 16,  8,  4,  6, 16, 14, 10, 14,  6, 13,
       16,  8, 13,  4,  6, 15, 14, 10])

In [107]:
# Tomando un trozo del array
trozo_arr = arr[0:3]
trozo_arr

array([3, 3, 3])

In [108]:
# copiando un array
copia_arr = arr.copy()
copia_arr

array([ 3,  3,  3,  8, 14,  7,  8, 16,  8,  4,  6, 16, 14, 10, 14,  6, 13,
       16,  8, 13,  4,  6, 15, 14, 10])

### Indexing en matrizes
***

In [109]:
arr_2d = arr.reshape(5,5)
arr_2d

array([[ 3,  3,  3,  8, 14],
       [ 7,  8, 16,  8,  4],
       [ 6, 16, 14, 10, 14],
       [ 6, 13, 16,  8, 13],
       [ 4,  6, 15, 14, 10]])

In [110]:
# Seleccionando la segunda fila
arr_2d[1]

array([ 7,  8, 16,  8,  4])

In [111]:
# Cambiando los valores de una fila completa
arr_2d[0] = arr_2d[0]*2
arr_2d

array([[ 6,  6,  6, 16, 28],
       [ 7,  8, 16,  8,  4],
       [ 6, 16, 14, 10, 14],
       [ 6, 13, 16,  8, 13],
       [ 4,  6, 15, 14, 10]])

In [112]:
# Obteniendo un valor especifico de la matriz
arr_2d[0][3]

16

In [116]:
# Obteniendo un trozo de la matriz
arr_2d[:2,3:]

array([[16, 28],
       [ 8,  4]])

In [119]:
# Obteniendo varias filas de la matriz (Se pueden obtener en el orden que sea)
arr_2d[[4,1,0]]

array([[ 4,  6, 15, 14, 10],
       [ 7,  8, 16,  8,  4],
       [ 6,  6,  6, 16, 28]])

In [121]:
# Que celdas de la matriz son mayores que 10?
arr_2d > 10

array([[False, False, False,  True,  True],
       [False, False,  True, False, False],
       [False,  True,  True, False,  True],
       [False,  True,  True, False,  True],
       [False, False,  True,  True, False]])

In [122]:
# Sumando la matriz consigo misma
arr_2d = arr_2d+arr_2d
arr_2d

array([[12, 12, 12, 32, 56],
       [14, 16, 32, 16,  8],
       [12, 32, 28, 20, 28],
       [12, 26, 32, 16, 26],
       [ 8, 12, 30, 28, 20]])

In [123]:
# Multiplicando la matriz consigo misma
arr_2d * arr_2d

array([[ 144,  144,  144, 1024, 3136],
       [ 196,  256, 1024,  256,   64],
       [ 144, 1024,  784,  400,  784],
       [ 144,  676, 1024,  256,  676],
       [  64,  144,  900,  784,  400]])

In [124]:
# Restando la matriz consigo misma
arr_2d = arr_2d-arr_2d
arr_2d

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [126]:
# Sumando un escalar a la matriz
arr_2d = arr_2d+6
arr_2d

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [127]:
# Elevando la matriz a algun escalar
arr_2d ** 5

array([[7776, 7776, 7776, 7776, 7776],
       [7776, 7776, 7776, 7776, 7776],
       [7776, 7776, 7776, 7776, 7776],
       [7776, 7776, 7776, 7776, 7776],
       [7776, 7776, 7776, 7776, 7776]], dtype=int32)

In [128]:
# La raiz cuadrada a cada elemento de la matriz
np.sqrt(arr_2d)

array([[2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974],
       [2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974],
       [2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974],
       [2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974],
       [2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974]])

In [131]:
# El seno de la matriz
sin = np.sin(arr_2d)
sin

array([[-0.2794155, -0.2794155, -0.2794155, -0.2794155, -0.2794155],
       [-0.2794155, -0.2794155, -0.2794155, -0.2794155, -0.2794155],
       [-0.2794155, -0.2794155, -0.2794155, -0.2794155, -0.2794155],
       [-0.2794155, -0.2794155, -0.2794155, -0.2794155, -0.2794155],
       [-0.2794155, -0.2794155, -0.2794155, -0.2794155, -0.2794155]])

In [132]:
# El coseno de la matriz
cos = np.cos(arr_2d)
cos

array([[0.96017029, 0.96017029, 0.96017029, 0.96017029, 0.96017029],
       [0.96017029, 0.96017029, 0.96017029, 0.96017029, 0.96017029],
       [0.96017029, 0.96017029, 0.96017029, 0.96017029, 0.96017029],
       [0.96017029, 0.96017029, 0.96017029, 0.96017029, 0.96017029],
       [0.96017029, 0.96017029, 0.96017029, 0.96017029, 0.96017029]])

In [133]:
# cos^2(matriz) + sen^2(matriz)
(cos**2)+(sin**2)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [134]:
# Todas las operaciones matematicas se pueden aplicar a los elementos del tipo array, 
# ·ya tenga 1, 2, n dimensiones.